### ISSUE TITLE
add config support for common tags

### ISSUE THREAD

**Issue by brharrington** [brharrington/snap-plugin-publisher-atlas#1]
There should be a way to specify the common tags as part of the configuration block for the publisher.

**Comment by brharrington** [comment]
The tags can be specified as part of the collect configuration, for example:

``` yaml
---
  version: 1
  schedule: 
    type: "simple"
    interval: "10s"
  workflow: 
    collect: 
      metrics: 
        /intel/psutil/*: {}
      config: null
      tags:
        /:
          "nf.region":  "us-east-1"
          "nf.node":    "i-12345"
      process: 
        - 
          plugin_name: "passthru"
          process: null
          publish: 
            - 
              plugin_name: "atlas"
              config: 
                uri: "http://localhost:7101/api/v1/publish"
```
